CREATE TABLE sales (
    Row_ID INT PRIMARY KEY,
    Order_ID VARCHAR(20) NOT NULL,
    Order_Date DATE NOT NULL,
    Ship_Date DATE NOT NULL,
    Ship_Mode VARCHAR(20),
    Customer_ID VARCHAR(10),
    Customer_Name VARCHAR(50),
    Segment VARCHAR(20),
    Country VARCHAR(50),
    City VARCHAR(50),
    State VARCHAR(50),
    Postal_Code VARCHAR(10),
    Region VARCHAR(20),
    Product_ID VARCHAR(20),
    Category VARCHAR(50),
    Sub_Category VARCHAR(50),
    Product_Name VARCHAR(255),
    Sales DECIMAL(10 , 2 ),
    Quantity INT,
    Discount DECIMAL(5 , 2 ),
    Profit DECIMAL(10 , 2 ),
    UNIQUE (Order_ID , Product_ID),
    INDEX idx_order_date (Order_Date),
    INDEX idx_customer_id (Customer_ID)
); 
